name: Docker Build and Push

on: [push]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - 
      name: checkout code
      uses: actions/checkout@v4

    - 
      name: login to DockerHub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: build and push Docker image
      uses: docker/build-push-action@v4
      with:
          context: docker-build-push
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-app:latest
     